(function(){
'use strict';
const VERSION='5.2.0-STRICT-IDB-LOCAL';
const CODE=(new URLSearchParams(location.search).get('code')||'TV-0001').trim();
const C=window.SUPABASE_CONFIG, API=C.url+'/rest/v1', KEY=C.key;
const H={apikey:KEY,Authorization:'Bearer '+KEY};
const DB='VitrineDigitalLocal52', STORE='media';
const SAVED_PLAYLIST='vd52_playlist_'+CODE, SAVED_FP='vd52_fp_'+CODE, COUNTERS='vd52_downloads';
const stage=document.getElementById('stage'), status=document.getElementById('status');
let activeItems=[], playIndex=0, playing=false, switching=false, currentEl=null, currentObjectUrl=null;
let playlistFp=localStorage.getItem(SAVED_FP)||'';
function safeJSON(v,f){try{return v?JSON.parse(v):f}catch(e){return f}}
function say(s){status.style.display='block';status.textContent=s;console.log('[VD5.2]',s)}
async function q(path){const r=await fetch(API+path,{headers:H,cache:'no-store'});if(!r.ok)throw new Error(await r.text());return r.json()}
function mediaUrl(m){return m.file_url||m.url||''}
function mediaFp(m){return [m.id,mediaUrl(m),m.updated_at||''].join('|')}
function listFp(pid,items){return pid+'::'+items.map(x=>[x.id,mediaFp(x),x.sort_order??x.position??0,x.duration||''].join('|')).join(';;')}
function dayToken(d){return ['Dom','Seg','Ter','Qua','Qui','Sex','Sab'][d.getDay()]}
function scheduleMatches(s,now){if(s.active===false)return false;const iso=now.getFullYear()+'-'+String(now.getMonth()+1).padStart(2,'0')+'-'+String(now.getDate()).padStart(2,'0');if(s.start_date&&iso<s.start_date)return false;if(s.end_date&&iso>s.end_date)return false;const days=String(s.days||'').split(',').map(x=>x.trim()).filter(Boolean);if(days.length&&!days.includes(dayToken(now)))return false;const t=String(now.getHours()).padStart(2,'0')+':'+String(now.getMinutes()).padStart(2,'0'),st=String(s.start_time||'').slice(0,5),et=String(s.end_time||'').slice(0,5);if(st&&et&&st<=et&&(t<st||t>et))return false;if(st&&et&&st>et&&(t>et&&t<st))return false;return true}
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(STORE))d.createObjectStore(STORE,{keyPath:'id'})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function idbGet(id){const db=await openDB();return new Promise((res,rej)=>{const t=db.transaction(STORE,'readonly'),r=t.objectStore(STORE).get(id);r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error);t.oncomplete=()=>db.close()})}
async function idbPut(v){const db=await openDB();return new Promise((res,rej)=>{const t=db.transaction(STORE,'readwrite');t.objectStore(STORE).put(v);t.oncomplete=()=>{db.close();res()};t.onerror=()=>rej(t.error)})}
function countDownload(m){const c=safeJSON(localStorage.getItem(COUNTERS),{});c[m.id]=(c[m.id]||0)+1;localStorage.setItem(COUNTERS,JSON.stringify(c));console.log('[VD5.2] DOWNLOAD REAL',m.name,'count=',c[m.id])}
async function ensureMedia(m,n,total){const fp=mediaFp(m),old=await idbGet(m.id);if(old&&old.fp===fp&&old.blob&&old.blob.size>0){console.log('[VD5.2] LOCAL OK',m.name,old.blob.size);return}say('Baixando '+n+'/'+total+' uma única vez: '+m.name);countDownload(m);const r=await fetch(mediaUrl(m),{cache:'no-store'});if(!r.ok)throw new Error('Download '+r.status+' '+m.name);const blob=await r.blob();if(!blob.size)throw new Error('Arquivo vazio: '+m.name);await idbPut({id:m.id,fp,blob,size:blob.size,name:m.name,savedAt:Date.now()});console.log('[VD5.2] SALVO LOCAL',m.name,blob.size)}
async function localObjectUrl(m){const x=await idbGet(m.id);if(!x||x.fp!==mediaFp(m)||!x.blob)throw new Error('Arquivo local ausente: '+m.name);return URL.createObjectURL(x.blob)}
function cleanupPlayback(){if(currentEl){try{currentEl.pause&&currentEl.pause();currentEl.removeAttribute&&currentEl.removeAttribute('src');currentEl.load&&currentEl.load()}catch(e){}currentEl=null}if(currentObjectUrl){try{URL.revokeObjectURL(currentObjectUrl)}catch(e){}currentObjectUrl=null}}
function next(){if(!activeItems.length)return;playIndex=(playIndex+1)%activeItems.length;play()}
async function play(){if(!activeItems.length){playing=false;return}playing=true;const x=activeItems[playIndex%activeItems.length];cleanupPlayback();stage.innerHTML='';try{const local=await localObjectUrl(x);currentObjectUrl=local;let el;if(x.type==='image'){el=new Image();el.src=local;currentEl=el;stage.appendChild(el);status.style.display='none';setTimeout(next,(x.duration||10)*1000)}else{el=document.createElement('video');el.autoplay=true;el.muted=true;el.playsInline=true;el.preload='auto';el.src=local;currentEl=el;el.onended=next;el.onerror=()=>{say('Erro no arquivo LOCAL: '+x.name);setTimeout(next,3000)};stage.appendChild(el);status.style.display='none';el.play().catch(e=>say('Play local: '+e.message))}}catch(e){say(e.message);setTimeout(next,3000)}}
function savePlaylist(items,fp){localStorage.setItem(SAVED_PLAYLIST,JSON.stringify(items));localStorage.setItem(SAVED_FP,fp);playlistFp=fp}
async function restoreLocal(){const saved=safeJSON(localStorage.getItem(SAVED_PLAYLIST),[]);if(!saved.length)return false;for(const m of saved){const x=await idbGet(m.id);if(!x||x.fp!==mediaFp(m)||!x.blob)return false}activeItems=saved;playIndex=0;say('Modo local: sem URL de vídeo do Supabase');play();return true}
async function fetchDesired(){const ss=await q('/screens?code=eq.'+encodeURIComponent(CODE)+'&active=eq.true&select=*');if(!ss.length)throw new Error('Tela '+CODE+' não encontrada/ativa');const screen=ss[0];const sch=await q('/schedules?active=eq.true&screen_id=eq.'+screen.id+'&select=*');if(sch.length&&!sch.some(s=>scheduleMatches(s,new Date())))return {outside:true};const chosen=sch.find(s=>scheduleMatches(s,new Date())),pid=(chosen&&chosen.playlist_id)||screen.playlist_id;if(!pid)throw new Error('Tela sem playlist');const pi=await q('/playlist_items?playlist_id=eq.'+pid+'&select=media_id,sort_order,position,duration&order=sort_order.asc');const ids=pi.map(x=>x.media_id).filter(Boolean);if(!ids.length)throw new Error('Playlist vazia');const ms=await q('/media?id=in.('+ids.join(',')+')&active=eq.true&select=id,name,type,url,file_url,duration,updated_at');const mm=Object.fromEntries(ms.map(x=>[x.id,x]));const items=pi.map(p=>Object.assign({},mm[p.media_id]||{},p)).filter(x=>x.id);return {outside:false,pid,items,fp:listFp(pid,items)}}
async function sync(){if(switching)return;switching=true;try{const d=await fetchDesired();if(d.outside){cleanupPlayback();stage.innerHTML='';activeItems=[];playing=false;say('Fora do horário de programação');return}if(d.fp===playlistFp&&activeItems.length){console.log('[VD5.2] Playlist igual: ZERO download');return}for(let i=0;i<d.items.length;i++)await ensureMedia(d.items[i],i+1,d.items.length);savePlaylist(d.items,d.fp);activeItems=d.items;playIndex=0;say('Conteúdo salvo. Reprodução estritamente local.');play()}catch(e){say('Sincronização: '+e.message);if(activeItems.length&&!playing)play()}finally{switching=false}}
async function removeSW(){if(!('serviceWorker'in navigator))return;for(const r of await navigator.serviceWorker.getRegistrations())await r.unregister()}
async function boot(){if(!('indexedDB'in window)){say('Navegador sem IndexedDB');return}try{await removeSW();await restoreLocal();await sync();setInterval(sync,360000)}catch(e){say('Falha ao iniciar: '+e.message)}}
boot();
})();
